CREATE TABLE orgao_expedidor(
   id    int       PRIMARY KEY,
   sigla varchar(8)   NOT NULL,
   nome  varchar(128) NOT NULL,
   tipo  int          NOT NULL -- 1 Orgão Federal -- 2 Orgão Regional -- 3 Orgão Municipal -- 4 Estrangeiro / Outro
);

CREATE INDEX idx_sigla ON orgao_expedidor (sigla);
CREATE INDEX idx_nome  ON orgao_expedidor (nome) ;

INSERT INTO orgao_expedidor VALUES (001, 'ABNC'   , 'Academia Brasileira de Neurocirurgia'                                   , 1);
INSERT INTO orgao_expedidor VALUES (002, 'AGU'    , 'Advocacia-Geral da União'                                               , 1);
INSERT INTO orgao_expedidor VALUES (003, 'ANAC'   , 'Agência Nacional de Aviação Civil'                                      , 1);
INSERT INTO orgao_expedidor VALUES (004, 'CAER'   , 'Clube de Aeronáutica'                                                   , 1);
INSERT INTO orgao_expedidor VALUES (005, 'CAU'    , 'Conselho de Arquitetura e Urbanismo'                                    , 1);
INSERT INTO orgao_expedidor VALUES (006, 'CBM'    , 'Corpo de Bombeiro Militar'                                              , 2);
INSERT INTO orgao_expedidor VALUES (007, 'CFA'    , 'Conselho Federal Administração'                                         , 1);
INSERT INTO orgao_expedidor VALUES (008, 'CFB'    , 'Conselho Federal de Biblioteconomia'                                    , 1);
INSERT INTO orgao_expedidor VALUES (009, 'CFBIO'  , 'Conselho Federal de Biologia'                                           , 1);
INSERT INTO orgao_expedidor VALUES (010, 'CFBM'   , 'Conselho Federal de Biomedicina'                                        , 1);
INSERT INTO orgao_expedidor VALUES (011, 'CFC'    , 'Conselho Federal de Contabilidade'                                      , 1);
INSERT INTO orgao_expedidor VALUES (012, 'CFESS'  , 'Conselho Federal de Serviço Social'                                     , 1);
INSERT INTO orgao_expedidor VALUES (013, 'CFF'    , 'Conselho Regional de Farmácia'                                          , 2);
INSERT INTO orgao_expedidor VALUES (014, 'CFFA'   , 'Conselho Federal de Fonoaudiologia'                                     , 1);
INSERT INTO orgao_expedidor VALUES (015, 'CFM'    , 'Conselho Federal de Medicina'                                           , 1);
INSERT INTO orgao_expedidor VALUES (016, 'CFMV'   , 'Conselho Federal de Medicina Veterinária'                               , 1);
INSERT INTO orgao_expedidor VALUES (017, 'CFN'    , 'Conselho Federal de Nutrição'                                           , 1);
INSERT INTO orgao_expedidor VALUES (018, 'CFO'    , 'Conselho Federal de Odontologia'                                        , 1);
INSERT INTO orgao_expedidor VALUES (019, 'CFP'    , 'Conselho Federal de Psicologia'                                         , 1);
INSERT INTO orgao_expedidor VALUES (020, 'CFQ'    , 'Conselho Regional de Química'                                           , 2);
INSERT INTO orgao_expedidor VALUES (021, 'CFT'    , 'Conselho Federal dos Técnicos Industriais'                              , 1);
INSERT INTO orgao_expedidor VALUES (022, 'CFTA'   , 'Conselho Federal dos Técnicos Agrícolas'                                , 1);
INSERT INTO orgao_expedidor VALUES (023, 'CGPI'   , 'Coordenação Geral de Privilégios e Imunidades'                          , 1);
INSERT INTO orgao_expedidor VALUES (024, 'CGPMAF' , 'Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras'   , 1);
INSERT INTO orgao_expedidor VALUES (025, 'CIPC'   , 'Centro de Inteligência da Polícia Civil'                                , 1);
INSERT INTO orgao_expedidor VALUES (026, 'CNIG'   , 'Conselho Nacional de Imigração'                                         , 1);
INSERT INTO orgao_expedidor VALUES (027, 'CNT'    , 'Confederação Nacional do Transporte'                                    , 1);
INSERT INTO orgao_expedidor VALUES (028, 'CNTV'   , 'Confederação Nacional de Vigilantes & Prestadores de Serviços'          , 1);
INSERT INTO orgao_expedidor VALUES (029, 'COFECI' , 'Conselho Federal de Corretores de Imóveis'                              , 1);
INSERT INTO orgao_expedidor VALUES (030, 'COFECON', 'Conselho Federal de Economia'                                           , 1);
INSERT INTO orgao_expedidor VALUES (031, 'COFEM'  , 'Conselho Federal de Museologia'                                         , 1);
INSERT INTO orgao_expedidor VALUES (032, 'COFEN'  , 'Conselho Federal de Enfermagem'                                         , 1);
INSERT INTO orgao_expedidor VALUES (033, 'COFFITO', 'Conselho Regional de Fisioterapia e Terapia Ocupacional'                , 2);
INSERT INTO orgao_expedidor VALUES (034, 'COMAER' , 'Comando da Aeronáutica'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (035, 'CONFE'  , 'Conselho Federal de Estatística'                                        , 1);
INSERT INTO orgao_expedidor VALUES (036, 'CONFEA' , 'Conselho Federal de Engenharia e Agronomia'                             , 1);
INSERT INTO orgao_expedidor VALUES (037, 'CONFEF' , 'Conselho Federal de Educação Física'                                    , 1);
INSERT INTO orgao_expedidor VALUES (038, 'CONFERE', 'Conselho Federal dos Representantes Comerciais'                         , 1);
INSERT INTO orgao_expedidor VALUES (039, 'CONRE'  , 'Conselho Regional de Estatística'                                       , 2);
INSERT INTO orgao_expedidor VALUES (040, 'CONRERP', 'Conselho Federal de Profissionais de Relações Públicas'                 , 1);
INSERT INTO orgao_expedidor VALUES (041, 'CORE'   , 'Conselho Regional dos Representantes Comerciais'                        , 2);
INSERT INTO orgao_expedidor VALUES (042, 'CORECON', 'Conselho Regional de Economia'                                          , 2);
INSERT INTO orgao_expedidor VALUES (043, 'COREM'  , 'Conselho Regional de Museologia'                                        , 2);
INSERT INTO orgao_expedidor VALUES (044, 'COREN'  , 'Conselho Regional de Enfermagem'                                        , 2);
INSERT INTO orgao_expedidor VALUES (045, 'CRA'    , 'Conselho Regional de Administração'                                     , 2);
INSERT INTO orgao_expedidor VALUES (046, 'CRAS'   , 'Centro de Referência de Assistência Social'                             , 1);
INSERT INTO orgao_expedidor VALUES (047, 'CRB'    , 'Conselho Regional de Biblioteconomia'                                   , 2);
INSERT INTO orgao_expedidor VALUES (048, 'CRBIO'  , 'Conselho Regional de Biologia'                                          , 2);
INSERT INTO orgao_expedidor VALUES (049, 'CRBM'   , 'Conselho Regional de Biomedicina'                                       , 2);
INSERT INTO orgao_expedidor VALUES (050, 'CRC'    , 'Conselho Regional de Contabilidade'                                     , 2);
INSERT INTO orgao_expedidor VALUES (051, 'CREA'   , 'Conselho Regional de Engenharia e Agronomia'                            , 2);
INSERT INTO orgao_expedidor VALUES (052, 'CRECI'  , 'Conselho Regional de Corretores de Imóveis'                             , 2);
INSERT INTO orgao_expedidor VALUES (053, 'CREF'   , 'Conselho Regional de Educação Física'                                   , 2);
INSERT INTO orgao_expedidor VALUES (054, 'CREFITO', 'Conselho Regional de Fisioterapia e Terapia Ocupacional'                , 2);
INSERT INTO orgao_expedidor VALUES (055, 'CRESS'  , 'Conselho Regional de Serviço Social'                                    , 2);
INSERT INTO orgao_expedidor VALUES (056, 'CRF'    , 'Conselho Regional de Farmácia'                                          , 2);
INSERT INTO orgao_expedidor VALUES (057, 'CRFA'   , 'Conselho Regional de Fonoaudiologia'                                    , 2);
INSERT INTO orgao_expedidor VALUES (058, 'CRM'    , 'Conselho Regional de Medicina'                                          , 2);
INSERT INTO orgao_expedidor VALUES (059, 'CRMV'   , 'Conselho Regional de Medicina Veterinária'                              , 2);
INSERT INTO orgao_expedidor VALUES (060, 'CRN'    , 'Conselho Regional de Nutrição'                                          , 2);
INSERT INTO orgao_expedidor VALUES (061, 'CRO'    , 'Conselho Regional de Odontologia'                                       , 2);
INSERT INTO orgao_expedidor VALUES (062, 'CRP'    , 'Conselho Regional de Psicologia'                                        , 2);
INSERT INTO orgao_expedidor VALUES (063, 'CRPRE'  , 'Conselho Regional de Profissionais de Relações Públicas'                , 2);
INSERT INTO orgao_expedidor VALUES (064, 'CRQ'    , 'Conselho Regional de Química'                                           , 2);
INSERT INTO orgao_expedidor VALUES (065, 'CRT'    , 'Conselho Regional dos Técnicos Industriais'                             , 2);
INSERT INTO orgao_expedidor VALUES (066, 'CRTA'   , 'Conselho Regional de Técnicos de Administração'                         , 2);
INSERT INTO orgao_expedidor VALUES (067, 'CTPS'   , 'Carteira de Trabalho e Previdência Social'                              , 2);
INSERT INTO orgao_expedidor VALUES (068, 'CV'     , 'Cartório Civil'                                                         , 3);
INSERT INTO orgao_expedidor VALUES (069, 'DELEMIG', 'Delegacia de Polícia de Imigração'                                      , 2);
INSERT INTO orgao_expedidor VALUES (070, 'DETRAN' , 'Departamento Estadual de Trânsito'                                      , 2);
INSERT INTO orgao_expedidor VALUES (071, 'DGPC'   , 'Diretoria Geral da Polícia Civil'                                       , 2);
INSERT INTO orgao_expedidor VALUES (072, 'DIC'    , 'Diretoria de Identificação Civil'                                       , 2);
INSERT INTO orgao_expedidor VALUES (073, 'DICC'   , 'Diretoria de Identificação Civil e Criminal'                            , 2);
INSERT INTO orgao_expedidor VALUES (074, 'DIREX'  , 'Diretoria Executiva'                                                    , 1);
INSERT INTO orgao_expedidor VALUES (075, 'DPF'    , 'Departamento de Polícia Federal'                                        , 1);
INSERT INTO orgao_expedidor VALUES (076, 'DPMAF'  , 'Divisão de Polícia Marítima, Aérea e de Fronteiras'                     , 1);
INSERT INTO orgao_expedidor VALUES (077, 'DPT'    , 'Departamento de Polícia Técnica Geral'                                  , 1);
INSERT INTO orgao_expedidor VALUES (078, 'DPTC'   , 'Departamento de Polícia Técnico Científica'                             , 1);
INSERT INTO orgao_expedidor VALUES (079, 'DREX'   , 'Delegacia Regional Executiva'                                           , 2);
INSERT INTO orgao_expedidor VALUES (080, 'DRT'    , 'Delegacia Regional do Trabalho'                                         , 2);
INSERT INTO orgao_expedidor VALUES (081, 'EB'     , 'Exército Brasileiro'                                                    , 1);
INSERT INTO orgao_expedidor VALUES (082, 'FAB'    , 'Força Aérea Brasileira'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (083, 'FENAJ'  , 'Federação Nacional dos Jornalistas'                                     , 1);
INSERT INTO orgao_expedidor VALUES (084, 'FGTS'   , 'Fundo de Garantia do Tempo de Serviço'                                  , 1);
INSERT INTO orgao_expedidor VALUES (085, 'FIPE'   , 'Fundação Instituto de Pesquisas Econômicas'                             , 1);
INSERT INTO orgao_expedidor VALUES (086, 'FLS'    , 'Fundação Lyndolpho Silva'                                               , 1);
INSERT INTO orgao_expedidor VALUES (087, 'FUNAI'  , 'Fundação Nacional do Índio'                                             , 1);
INSERT INTO orgao_expedidor VALUES (088, 'GEJSP'  , 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO orgao_expedidor VALUES (089, 'GEJSPC' , 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO orgao_expedidor VALUES (090, 'GEJUSPC', 'Gerência de Estado de Justiça, Segurança Pública e Cidadania'           , 1);
INSERT INTO orgao_expedidor VALUES (091, 'GESP'   , 'Gerência de Estado de Segurança Pública'                                , 1);
INSERT INTO orgao_expedidor VALUES (092, 'GOVGO'  , 'Governo do Estado de Goiás'                                             , 1);
INSERT INTO orgao_expedidor VALUES (093, 'I CLA'  , 'Carteira de Identidade Classista'                                       , 1);
INSERT INTO orgao_expedidor VALUES (094, 'ICP'    , 'Instituto de Polícia Científica'                                        , 1);
INSERT INTO orgao_expedidor VALUES (095, 'IDAMP'  , 'Instituto de Identificação Dr. Aroldo Mendes Paiva'                     , 1);
INSERT INTO orgao_expedidor VALUES (096, 'IFP'    , 'Instituto Félix Pacheco'                                                , 1);
INSERT INTO orgao_expedidor VALUES (097, 'IGP'    , 'Instituto Geral de Perícias'                                            , 1);
INSERT INTO orgao_expedidor VALUES (098, 'IIACM'  , 'Instituto de Identificação Aderson Conceição de Melo'                   , 1);
INSERT INTO orgao_expedidor VALUES (099, 'IICC'   , 'Instituto de Identificação Civil e Criminal'                            , 1);
INSERT INTO orgao_expedidor VALUES (100, 'IICCECF', 'Instituto de Identificação Civil e Criminal Engrácia da Costa Francisco', 1);
INSERT INTO orgao_expedidor VALUES (101, 'IICM'   , 'Instituto de Identificação Carlos Menezes'                              , 1);
INSERT INTO orgao_expedidor VALUES (102, 'IIGP'   , 'Instituto de Identificação Gonçalo Pereira'                             , 1);
INSERT INTO orgao_expedidor VALUES (103, 'IIJDM'  , 'Instituto de Identificação João de Deus Martins'                        , 1);
INSERT INTO orgao_expedidor VALUES (104, 'IIRGD'  , 'Instituto de Identificação Ricardo Gumbleton Daunt'                     , 1);
INSERT INTO orgao_expedidor VALUES (105, 'IIPC'   , 'Instituto de Identificação da Polícia Civil'                            , 1);
INSERT INTO orgao_expedidor VALUES (106, 'IIPM'   , 'Instituto de Identificação Pedro Mello'                                 , 1);
INSERT INTO orgao_expedidor VALUES (107, 'IIRHM'  , 'Instituto de Identificação Raimundo Hermínio de Melo'                   , 1);
INSERT INTO orgao_expedidor VALUES (108, 'IITB'   , 'Instituto de Identificação Tavares Buril'                               , 1);
INSERT INTO orgao_expedidor VALUES (109, 'IML'    , 'Instituto Médico-Legal'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (110, 'INI'    , 'Instituto Nacional de Identificação'                                    , 1);
INSERT INTO orgao_expedidor VALUES (111, 'IPF'    , 'Instituto Pereira Faustino'                                             , 1);
INSERT INTO orgao_expedidor VALUES (112, 'ITCP'   , 'Instituto Técnico-Científico de Perícia'                                , 1);
INSERT INTO orgao_expedidor VALUES (113, 'ITEP'   , 'Instituto Técnico-Científico de Perícia'                                , 1);
INSERT INTO orgao_expedidor VALUES (114, 'MAER'   , 'Ministério da Aeronáutica'                                              , 1);
INSERT INTO orgao_expedidor VALUES (115, 'MB'     , 'Marinha do Brasil'                                                      , 1);
INSERT INTO orgao_expedidor VALUES (116, 'MD'     , 'Ministério da Defesa'                                                   , 1);
INSERT INTO orgao_expedidor VALUES (117, 'MDS'    , 'Ministério da Cidadania'                                                , 1);
INSERT INTO orgao_expedidor VALUES (118, 'MEC'    , 'Ministério da Educação e Cultura'                                       , 1);
INSERT INTO orgao_expedidor VALUES (119, 'MEX'    , 'Ministério do Exército'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (120, 'MINDEF' , 'Ministério da Defesa'                                                   , 1);
INSERT INTO orgao_expedidor VALUES (121, 'MJ'     , 'Ministério da Justiça'                                                  , 1);
INSERT INTO orgao_expedidor VALUES (122, 'MM'     , 'Ministério da Marinha'                                                  , 1);
INSERT INTO orgao_expedidor VALUES (123, 'MMA'    , 'Ministério da Marinha'                                                  , 1);
INSERT INTO orgao_expedidor VALUES (124, 'MP'     , 'Ministério Público'                                                     , 1);
INSERT INTO orgao_expedidor VALUES (125, 'MPAS'   , 'Ministério da Previdência e Assistência Social'                         , 1);
INSERT INTO orgao_expedidor VALUES (126, 'MPE'    , 'Ministério Público Estadual'                                            , 1);
INSERT INTO orgao_expedidor VALUES (127, 'MPF'    , 'Ministério Público Federal'                                             , 1);
INSERT INTO orgao_expedidor VALUES (128, 'MPT'    , 'Ministério Público do Trabalho'                                         , 1);
INSERT INTO orgao_expedidor VALUES (129, 'MRE'    , 'Ministério das Relações Exteriores'                                     , 1);
INSERT INTO orgao_expedidor VALUES (130, 'MT'     , 'Ministério do Trabalho'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (131, 'MTE'    , 'Ministério da Economia'                                                 , 1);
INSERT INTO orgao_expedidor VALUES (132, 'MTPS'   , 'Ministério do Trabalho e Previdência Social'                            , 1);
INSERT INTO orgao_expedidor VALUES (133, 'NUMIG'  , 'Núcleo de Polícia de Imigração'                                         , 2);
INSERT INTO orgao_expedidor VALUES (134, 'OAB'    , 'Ordem dos Advogados do Brasil'                                          , 1);
INSERT INTO orgao_expedidor VALUES (135, 'OMB'    , 'Ordens dos Músicos do Brasil'                                           , 1);
INSERT INTO orgao_expedidor VALUES (136, 'PC'     , 'Polícia Civil'                                                          , 2);
INSERT INTO orgao_expedidor VALUES (137, 'PF'     , 'Polícia Federal'                                                        , 1);
INSERT INTO orgao_expedidor VALUES (138, 'PGFN'   , 'Procuradoria Geral da Fazenda Nacional'                                 , 1);
INSERT INTO orgao_expedidor VALUES (139, 'PM'     , 'Polícia Militar'                                                        , 2);
INSERT INTO orgao_expedidor VALUES (140, 'POLITEC', 'Perícia Oficial e Identificação Técnica'                                , 1);
INSERT INTO orgao_expedidor VALUES (141, 'PRF'    , 'Polícia Rodoviária Federal'                                             , 1);
INSERT INTO orgao_expedidor VALUES (142, 'PTC'    , 'Polícia Tecnico-Científica'                                             , 1);
INSERT INTO orgao_expedidor VALUES (143, 'SCC'    , 'Secretaria de Estado da Casa Civil'                                     , 2);
INSERT INTO orgao_expedidor VALUES (144, 'SCJDS'  , 'Secretaria Coordenadora de Justiça e Defesa Social'                     , 2);
INSERT INTO orgao_expedidor VALUES (145, 'SDS'    , 'Secretaria de Defesa Social'                                            , 2);
INSERT INTO orgao_expedidor VALUES (146, 'SECC'   , 'Secretaria de Estado da Casa Civil'                                     , 2);
INSERT INTO orgao_expedidor VALUES (147, 'SECCDE' , 'Secretaria de Estado da Casa Civil e Desenvolvimento Econômico'         , 2);
INSERT INTO orgao_expedidor VALUES (148, 'SEDS'   , 'Secretaria de Estado da Defesa Social'                                  , 2);
INSERT INTO orgao_expedidor VALUES (149, 'SEGUP'  , 'Secretaria de Estado da Segurança Pública e da Defesa Social'           , 2);
INSERT INTO orgao_expedidor VALUES (150, 'SEJSP'  , 'Secretaria de Estado de Justiça e Segurança Pública'                    , 2);
INSERT INTO orgao_expedidor VALUES (151, 'SEJUC'  , 'Secretaria de Estado da Justica'                                        , 2);
INSERT INTO orgao_expedidor VALUES (152, 'SEJUSP' , 'Secretaria de Estado de Justiça e Segurança Pública'                    , 2);
INSERT INTO orgao_expedidor VALUES (153, 'SEPC'   , 'Secretaria de Estado da Polícia Civil'                                  , 2);
INSERT INTO orgao_expedidor VALUES (154, 'SES'    , 'Secretaria de Estado da Segurança'                                      , 2);
INSERT INTO orgao_expedidor VALUES (155, 'SESC'   , 'Secretaria de Estado da Segurança e Cidadania'                          , 2);
INSERT INTO orgao_expedidor VALUES (156, 'SESDC'  , 'Secretaria de Estado da Segurança, Defesa e Cidadania'                  , 2);
INSERT INTO orgao_expedidor VALUES (157, 'SESDEC' , 'Secretaria de Estado da Segurança, Defesa e Cidadania'                  , 2);
INSERT INTO orgao_expedidor VALUES (158, 'SESEG'  , 'Secretaria Estadual de Segurança'                                       , 2);
INSERT INTO orgao_expedidor VALUES (159, 'SESP'   , 'Secretaria de Estado da Segurança Pública'                              , 2);
INSERT INTO orgao_expedidor VALUES (160, 'SESPAP' , 'Secretaria de Estado da Segurança Pública e Administração Penitenciária', 2);
INSERT INTO orgao_expedidor VALUES (161, 'SESPDC' , 'Secretaria de Estado de Segurança Publica e Defesa do Cidadão'          , 2);
INSERT INTO orgao_expedidor VALUES (162, 'SESPDS' , 'Secretaria de Estado de Segurança Pública e Defesa Social'              , 2);
INSERT INTO orgao_expedidor VALUES (163, 'SGPC'   , 'Superintendência Geral de Polícia Civil'                                , 1);
INSERT INTO orgao_expedidor VALUES (164, 'SGPJ'   , 'Superintendência Geral de Polícia Judiciária'                           , 1);
INSERT INTO orgao_expedidor VALUES (165, 'SIM'    , 'Serviço de Identificação da Marinha'                                    , 1);
INSERT INTO orgao_expedidor VALUES (166, 'SJ'     , 'Secretaria da Justiça'                                                  , 2);
INSERT INTO orgao_expedidor VALUES (167, 'SJCDH'  , 'Secretaria da Justiça e dos Direitos Humanos'                           , 2);
INSERT INTO orgao_expedidor VALUES (168, 'SJDS'   , 'Secretaria Coordenadora de Justiça e Defesa Social'                     , 2);
INSERT INTO orgao_expedidor VALUES (169, 'SJS'    , 'Secretaria da Justiça e Segurança'                                      , 2);
INSERT INTO orgao_expedidor VALUES (170, 'SJTC'   , 'Secretaria da Justiça do Trabalho e Cidadania'                          , 2);
INSERT INTO orgao_expedidor VALUES (171, 'SJTS'   , 'Secretaria da Justiça do Trabalho e Segurança'                          , 2);
INSERT INTO orgao_expedidor VALUES (172, 'SNJ'    , 'Secretaria Nacional de Justiça / Departamento de Estrangeiros'          , 2);
INSERT INTO orgao_expedidor VALUES (173, 'SPMAF'  , 'Serviço de Polícia Marítima, Aérea e de Fronteiras'                     , 2);
INSERT INTO orgao_expedidor VALUES (174, 'SPTC'   , 'Secretaria de Polícia Técnico-Científica'                               , 2);
INSERT INTO orgao_expedidor VALUES (175, 'SRDPF'  , 'Superintendência Regional do Departamento de Polícia Federal'           , 2);
INSERT INTO orgao_expedidor VALUES (176, 'SRF'    , 'Receita Federal'                                                        , 1);
INSERT INTO orgao_expedidor VALUES (177, 'SRTE'   , 'Superintendência Regional do Trabalho'                                  , 2);
INSERT INTO orgao_expedidor VALUES (178, 'SSDC'   , 'Secretaria da Segurança, Defesa e Cidadania'                            , 2);
INSERT INTO orgao_expedidor VALUES (179, 'SSDS'   , 'Secretaria da Segurança e da Defesa Social'                             , 2);
INSERT INTO orgao_expedidor VALUES (180, 'SSI'    , 'Secretaria de Segurança e Informações'                                  , 2);
INSERT INTO orgao_expedidor VALUES (181, 'SSP'    , 'Secretaria de Segurança Pública'                                        , 2);
INSERT INTO orgao_expedidor VALUES (182, 'SSPCGP' , 'Secretaria de Segurança Pública e Coordenadoria Geral de Perícias'      , 2);
INSERT INTO orgao_expedidor VALUES (183, 'SSPDC'  , 'Secretaria de Segurança Pública e Defesa do Cidadão'                    , 2);
INSERT INTO orgao_expedidor VALUES (184, 'SSPDS'  , 'Secretaria de Segurança Pública e Defesa Social'                        , 2);
INSERT INTO orgao_expedidor VALUES (185, 'SSPPC'  , 'Secretaria de Segurança Pública Polícia Civil'                          , 2);
INSERT INTO orgao_expedidor VALUES (186, 'SUSEP'  , 'Superintendência de Seguros Privados'                                   , 1);
INSERT INTO orgao_expedidor VALUES (187, 'SUSEPE' , 'Superintendência dos Serviços Penitenciários'                           , 2);
INSERT INTO orgao_expedidor VALUES (188, 'TJ'     , 'Tribunal de Justiça'                                                    , 1);
INSERT INTO orgao_expedidor VALUES (189, 'TJAEM'  , 'Tribunal Arbitral e Mediação dos Estados Brasileiros'                   , 1);
INSERT INTO orgao_expedidor VALUES (190, 'TRE'    , 'Tribunal Regional Eleitoral'                                            , 2);
INSERT INTO orgao_expedidor VALUES (191, 'TRF'    , 'Tribunal Regional Federal'                                              , 2);
INSERT INTO orgao_expedidor VALUES (192, 'TSE'    , 'Tribunal Superior Eleitoral'                                            , 1);
INSERT INTO orgao_expedidor VALUES (193, 'XXX'    , 'Orgão Estrangeiro'                                                      , 4);
INSERT INTO orgao_expedidor VALUES (194, 'ZZZ'    , 'Outro'                                                                  , 4);